### ISSUE TITLE
presidential election data

### ISSUE THREAD

**Issue by brandly** [elliottmorris/politicaldata#4]
hey! i came across this repo via [an article you wrote](https://www.thecrosstab.com/project/r-politics-guide/guide.html)

i was curious where you got [your data from](https://github.com/elliottmorris/politicaldata/commit/bc3c099f410b395cee3a04ecf101728ead26f279). i have some [election data here](https://github.com/brandly/presidential-election-data/tree/master/json) dating back to 1900, if it's any use to you, but it's mainly electoral votes.

**Comment by elliottmorris** [comment]
Hi, Matt. 

Thanks very much for your email. These data came from the MIT Election and Data Science lab. They don't have electoral votes, though, so that would be pretty darn useful. I'll keep this issue open and implement in a commit this weekend.

Elliott

**Comment by brandly** [comment]
i just took a look at [where you got your data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX). it's far more expansive than the data i've collected, including popular votes for all candidates on a per-state basis. i just have total electoral votes since 1900, and total popular votes since 1992. maybe it's still of some use to you 😄
