### ISSUE TITLE
house_results is incorrect in CRAN version

### ISSUE THREAD

**Issue by NickCH-K** [elliottmorris/politicaldata#5]
The package looks very interesting! I was writing a homework assignment using the house_results data, but the version on CRAN appears to be unusable. The dem/rep/other values are on the order of e-06 to e-10 and don't add up to anything near 1. For example, row 1 of the data has

dem | other | rep
-----|-------|-----
2.447125e-06 | 2.089725e-08 | 5.991642e-06

The GitHub version looks accurate, but you may want to post a CRAN update.

**Comment by elliottmorris** [comment]
Hi Nick,

Yes, unfortunately, this slipped through the cracks in the first set of tests. I've added new tests to ensure it does not happen again. Sorry for the homework troubles!

Elliott
