### ISSUE TITLE
9 copies of 2018 data in house_results

### ISSUE THREAD

**Issue by NickCH-K** [elliottmorris/politicaldata#6]
Hi again!

Thanks for fixing the issue with the house_results data, but a new one has popped up in the CRAN version!

Every 2018 observation appears to be repeated 9 times (with minor variation in that observations in which a particular party fields no candidate is sometimes 0 and sometimes NA).

For illustration:
![image](https://user-images.githubusercontent.com/44816781/54588813-2d6b8080-49e1-11e9-9fb6-b428e8ad774e.png)
![image](https://user-images.githubusercontent.com/44816781/54588788-1f1d6480-49e1-11e9-9694-44a2bae46ed3.png)

**Comment by elliottmorris** [comment]
@NickCH-K 

Thanks for pointing out this issue. I'm having an annoying time finding all the bugs with these data. I've just pushed a new update to the GitHub repo, which you can install with the usual `devtools` workflow (see the readme), and the new version is going to CRAN on Friday.

Thanks again,

Elliott
